# Домащнее задание

1. Реализовать логическую функцию на 
    * бинарных нейронах
    * биполярных нейронах
$$ y = \overline{ \left( \overline{x_1} + \overline{x_2 x_3} \, x_4 \right) } + \overline{x_2} \, x_3 \, x_4 $$
2. Реализовать XOR на двух бинарных нейронах
$$ y = \bar{x_1} x_2 + x_1 \bar{x_2} $$

In [51]:
import numpy as np
import pandas as pd

In [52]:
class Neuron:
    def __init__(self, weights, bias):
        self.weights = np.array(weights, dtype=float)
        self.bias = np.array(bias, dtype=float)
    
    def forward(self, inputs):
        inputs = np.array(inputs, dtype=float)
        return self.bias + np.dot(self.weights, inputs)

class BinarNeuron(Neuron):
    def activate(self, inputs):
        out = self.forward(inputs)
        return 1 if out >= 0 else 0

    def __call__(self, inputs):
        return self.activate(inputs)

class BipolarNeuron(Neuron):
    def activate(self, inputs):
        out = self.forward(inputs)
        return 1 if out >= 0 else -1

    def __call__(self, inputs):
        return self.activate(inputs)

class NotBinarNeuron(BinarNeuron):
    def __init__(self):
        super().__init__(weights=[-2], bias=[1])

class AndBinarNeuron(BinarNeuron):
    def __init__(self):
        super().__init__(weights=[1, 1], bias=[-1.5])

class OrBinarNeuron(BinarNeuron):
    def __init__(self):
        super().__init__(weights=[1, 1], bias=[-0.5])

## Task 1(a)

In [53]:
class FirstNeuralNetwork:
    def __init__(self):
        self.n1 = NotBinarNeuron()
        self.n2 = AndBinarNeuron()
        self.n3 = NotBinarNeuron()
        self.n4 = AndBinarNeuron()
        self.n5 = OrBinarNeuron()
        self.n6 = NotBinarNeuron()
        self.n7 = NotBinarNeuron()
        self.n8 = AndBinarNeuron()
        self.n9 = AndBinarNeuron()
        self.n10 = OrBinarNeuron()
    
    def forward(self, x1, x2, x3, x4):
        not_x1 = self.n1(x1)
        and_x2_x3 = self.n2([x2, x3])
        not_n2 = self.n3(and_x2_x3)
        and_n3_x4 = self.n4([not_n2, x4])
        or_n1_n4 = self.n5([not_x1, and_n3_x4])
        not_n5 = self.n6(or_n1_n4)

        not_x2 = self.n7(x2)
        and_n7_x3 = self.n8([not_x2, x3])
        and_n8_x4 = self.n9([and_n7_x3, x4])
        or_n6_n9 = self.n10([not_n5, and_n8_x4])

        return or_n6_n9

def first_solution(x1, x2, x3, x4):
    return int(not (not x1 or not (x2 and x3) and x4) or not x2 and x3 and x4)

df = pd.DataFrame(columns=['x1', 'x2', 'x3', 'x4', 'true_y', 'neuron_y'])
network1 = FirstNeuralNetwork()

for x1 in range(0, 2):
    for x2 in range(0, 2):
        for x3 in range(0, 2):
            for x4 in range(0, 2):
                y = network1.forward(x1, x2, x3, x4)
                true_y = first_solution(x1, x2, x3, x4)
                df = pd.concat([df, pd.DataFrame({'x1': [x1], 'x2': [x2], 'x3': [x3], 'x4': [x4],
                                                   'true_y': [true_y], 'neuron_y': [y]})], ignore_index=True)

df

   x1 x2 x3 x4 true_y neuron_y
0   0  0  0  0      0        0
1   0  0  0  1      0        0
2   0  0  1  0      0        0
3   0  0  1  1      1        1
4   0  1  0  0      0        0
5   0  1  0  1      0        0
6   0  1  1  0      0        0
7   0  1  1  1      0        0
8   1  0  0  0      1        1
9   1  0  0  1      0        0
10  1  0  1  0      1        1
11  1  0  1  1      1        1
12  1  1  0  0      1        1
13  1  1  0  1      0        0
14  1  1  1  0      1        1
15  1  1  1  1      1        1

## Task 1(b)

In [54]:
class SecondNeuralNetwork:
    def __init__(self):
        self.n1 = BipolarNeuron([-2], 1)
        self.n2 = BipolarNeuron([1, 1], -1.5)
        self.n3 = BipolarNeuron([-1], 0)
        self.n4 = BipolarNeuron([1, 1], -1.5)
        self.n5 = BipolarNeuron([1, 1], 0.5)
        self.n6 = BipolarNeuron([-1], 0)
        self.n7 = BipolarNeuron([-2], 1)
        self.n8 = BipolarNeuron([1, 1], -1.5)
        self.n9 = BipolarNeuron([1, 1], -1.5)
        self.n10 = BipolarNeuron([1, 1], 0.5)

    def forward(self, x1, x2, x3, x4):
        not_x1 = self.n1(x1)
        and_x2_x3 = self.n2([x2, x3])
        not_n2 = self.n3(and_x2_x3)
        and_n3_x4 = self.n4([not_n2, x4])
        or_n1_n4 = self.n5([not_x1, and_n3_x4])
        not_n5 = self.n6(or_n1_n4)

        not_x2 = self.n7(x2)
        and_n7_x3 = self.n8([not_x2, x3])
        and_n8_x4 = self.n9([and_n7_x3, x4])
        or_n6_n9 = self.n10([not_n5, and_n8_x4])

        return or_n6_n9

def second_solution(x1, x2, x3, x4):
    return int(not (not x1 or not (x2 and x3) and x4) or not x2 and x3 and x4)

df = pd.DataFrame(columns=['x1', 'x2', 'x3', 'x4', 'true_y', 'neuron_y'])
network1 = SecondNeuralNetwork()

for x1 in range(0, 2):
    for x2 in range(0, 2):
        for x3 in range(0, 2):
            for x4 in range(0, 2):
                y = network1.forward(x1, x2, x3, x4)
                true_y = second_solution(x1, x2, x3, x4)
                df = pd.concat([df, pd.DataFrame({'x1': [x1], 'x2': [x2], 'x3': [x3], 'x4': [x4],
                                                   'true_y': [true_y], 'neuron_y': [y]})], ignore_index=True)

df

   x1 x2 x3 x4 true_y neuron_y
0   0  0  0  0      0       -1
1   0  0  0  1      0       -1
2   0  0  1  0      0       -1
3   0  0  1  1      1        1
4   0  1  0  0      0       -1
5   0  1  0  1      0       -1
6   0  1  1  0      0       -1
7   0  1  1  1      0       -1
8   1  0  0  0      1        1
9   1  0  0  1      0       -1
10  1  0  1  0      1        1
11  1  0  1  1      1        1
12  1  1  0  0      1        1
13  1  1  0  1      0       -1
14  1  1  1  0      1        1
15  1  1  1  1      1        1

## Task 2

In [ ]:
class ThirdNeuralNetwork:
    def __init__(self):
        self.n1 = BinarNeuron([-1, -1], 0.5)
        self.n2 = BinarNeuron([-2, -1, -1], 1.5)

    def forward(self, x1, x2):
        print(self.n1([x1, x2]))
        return self.n2([self.n1([x1, x2]), x1, x2])

def second_solution(x1, x2):
    return int(x1 and not x2 or not x1 and x2)

df = pd.DataFrame(columns=['x1', 'x2', 'true_y', 'neuron_y'])
network1 = ThirdNeuralNetwork()

for x1 in range(0, 2):
    for x2 in range(0, 2):
        y = network1.forward(x1, x2)
        true_y = second_solution(x1, x2)
        df = pd.concat([df, pd.DataFrame({'x1': [x1], 'x2': [x2],
                                            'true_y': [true_y], 'neuron_y': [y]})], ignore_index=True)

df

  x1 x2 true_y neuron_y
0  0  0      0        0
1  0  1      1        1
2  1  0      1        1
3  1  1      0        0